name: Back-end

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/webstu-back-end
          git fetch origin
          git checkout production
          git pull 
          npm install
          npx prisma generate
          npm run build
          pm2 reload back --update-env
